version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./logs/:/usr/src/app/logs/
    restart: unless-stopped
    ports:
      - "8080:8000"
    environment:
      ORIGIN_DOMAIN: http://127.0.0.1:8080

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: w6a12da124BP2
      MONGO_INITDB_DATABASE: Database
    volumes:
      - ./data/mongo:/data/db